# DeepVision Crowd Monitor - Essential Configuration

# Model
model:
  name: "csrnet"
  pretrained: true

# Dataset
data:
  root_dir: "Dataset/ShanghaiTech/part_B/train_data"
  image_size: [512, 512]
  num_workers: 2

# Training
training:
  batch_size: 6
  num_epochs: 75
  learning_rate: 1e-5
  weight_decay: 1e-4
  train_split: 0.8
  
  loss:
    mse_weight: 1.0
    count_weight: 0.01

# Logging
logging:
  results_dir: "results"
  save_interval: 10
  
  wandb:
    project: "crowd-density-part-b"
    entity: null
    log_interval: 10