# DeepVision Crowd Monitor - Essential Configuration

# Model
model:
  name: "csrnet"
  pretrained: true

# Dataset
data:
  root_dir: "Dataset/ShanghaiTech/part_B/train_data"
  image_size: [512, 512]
  num_workers: 2

# Training
training:
  batch_size: 4
  num_epochs: 50
  learning_rate: !!float 5e-5
  weight_decay: !!float 5e-4
  train_split: 0.8
  device: "mps"
  
  mixed_precision: false  
  gradient_accumulation: 2  
  
  loss:
    mse_weight: 1.0
    count_weight: 0.01

# Logging
logging:
  results_dir: "results"
  save_interval: 10
  
  wandb:
    project: "crowd-density"
    entity: null
    log_interval: 5

